### PR TITLE
Settings persistance, New map Images, Hacky hotkeys and a widget

### PR DESCRIPTION
**Pull request by akamal**
Pretty much everything that is configurable now gets saved and restored between sessions; There's a working (if nasty) hotkey implementation, and a rudimentary widget to demonstrate them;  new map images; and a few other minor tweaks:

akStatusWidget - very wip
    Displays current grenades and subset of aid items
    Creates hotkeys for:
    g: Cycle available grenades
    [home]: Use RadAway
    [insert]: Use Stimpak
    [PgUp]: Use Jet

LocalMapWidget Layout tweak
    removed unecessary margins

pypipboyapp.py, hotkeymanager.py HotKey Support

GlobalMapWidget
    Amended filepath and offsets for 4k map image
    Added 4k map files (standard and with threatlevel) from:
    https://www.reddit.com/r/fo4/comments/3tkmog/i_made_a_map/
    Corrected map bounds for 4k maps
    Implemented toggle threat level

LocalMapWidget Settings
    Zoom, Enabled and Splitter posiiton

GlobalMapWidget Settings
    Persist settings for Zoom level, AutoColor, Custom Color, StickyLabels,
    PowerArmorMarker, LocationMarkers, LocationVisibilityCheat,
    CenterPlayer, Splitter State

MainWindow Settings
    Save last connection, Auto-Connect, Auto-load last style

### CODE REVIEW

**Comment by matzman666** [comment]
Have imported your branch into my private repo and will now go through your modifications. Will commit to master as soon as I am finished. There are already two things I noticed:
x) Which license to the maps you committed have? I think the thread-level one is from the survival guide and under copyright.
x) The hotkey stuff is Windows only and we need to find a way to disable it for non-Windows systems.

**Comment by akamal** [comment]
There’s a link to where I found the maps in the pull request notes, no licence mentioned but they’re being freely distributed. That said, I’d understand if you’re not comfortable including them without a clear licence.

Leave the hotkey stuff out for now. I’ve managed to get it working using a keyboard hook instead of registerHotkey, and I’m most of the way to isolating it in its own widget. That’s still going to need pywin32, but hopefully if it’s all self-contained in a widget that’ll make it easier to isolate? 

ak

**Comment by matzman666** [comment]
I have now created a nonfree repository for GPL violating stuff, and moved the maps there. I will include them in the releases until someone complains.

I added some code that only loads the hotkey stuff on Windows.

**Comment by akamal** [comment]
Hi, 

Good idea, I don’t think I’d fully thought through the implications of their questionable status and your repo being licenced under GPL, sorry about that.

Anyway, I’ve sent you another pull request now that I’ve got the hotkeys working with the keyboard hook, a UI built, and fully self-contained without being reliant on changes in pypipboyapp.py.

Let me know if I’m going about this in a way that’s convoluted or making life difficult; still finding my way around with git (and python and qt!) at the mo.

cheers

ak

**Pull request closed without merging**
