### PR TITLE
Doctors Bag Widget; Map Location Notes; Bug fixes to SmallPlayInfo and Hotkeys

### PR DESCRIPTION
**Pull request by akamal**
Doctors Bag Widget: Displays and allows quick activation of aid items
Global Map: Can add notes to location markers (right-click, Add\Edit Note) 
Global Map: Shows cleared state and presence of player note with overlay icons on location markers
[using world-coords to identify the marker for this (and the notes) feels wrong, but I'm not sure what else is unique and consistent across sessions and map resolution changes - do you thing LocationFormId or LocationMarkerFormId would be safe\appropriate?]
Global Map: Saved state of labels that have been made sticky for specific location markers
Global Map: Changed display style of labels - feel free to ignore this if you don't like it!
SmallPlayerInfo: Change to displayed location name when in named cells
Hotkeys: Phantom Item checks

### CODE REVIEW

**Comment by matzman666** [comment]
Merged with commit 34a9ab61b00142504e537fff77199fb560814d71 (Entered wrong request number).

**Comment by matzman666** [comment]
I not only entered the wrong request number, I also forgot to pull some changes. Fixed in commit https://github.com/matzman666/PyPipboyApp/commit/70ef438cf7cb8fc4cbd36fe72be1714e29159f79.

Regarding doctors' bag: Iterating over the 'number' sections in the inventory section is dangerous as there may be invalid items. The best way is to iterate over the sortedIDS, I provided some utility function in the inventoryutils module (See changes in commit a9709fd2bdd2fee3a2bc967d8df6058484584367).

You beat me with adding notes to the global map. I was thinking about how to implement them, and you already did. Good work.

**Comment by matzman666** [comment]
I see, I didn't forget some changes, they were added during me merging and pushing.

Since we are now more or less feature complete (at least the basic functionality), I would like to release a new version tomorrow.

**Comment by akamal** [comment]
Yeah, looks like I pushed my commits whilst you were merging the last set. 

Next thing I was thinking of looking at was the ability to add markers (and therefore notes) to arbitrary points on the map, obviously these wouldn't be visible in game but I'd still find them useful. Any thoughts?

Thanks for the tip about not iterating over the inventory sections, I'll get my other widgets updated in time for the release after this one. Does the inventoryutils.inventoryGetItems method handle checking that the items are valid (i.e. that they are present in sortedIDs), or do I still need to be checking that separately?

**Comment by matzman666** [comment]
Note markers on arbitrary points are a very good idea. We should definitely do this.

inventoryGetItems() does verify all items, no need to check yourself. I already updated the equippedandgrenades widget while fixing a race condition bug.

**Pull request closed without merging**
