### PR TITLE
Better indication of collected collectables, reduced resource usage, redundant code removal

### PR DESCRIPTION
**Pull request by akamal**
CollectableMarkers become darker and drop to the bottom of the zOrder when marked as collected (more obvious that just the tick, and helps with clutter)

Removed colouriseIcon from MarkerBase and switched callers to use the almost identical ImageFactory.colorizeImage (necessitated reversing the pngs)

LocationMarker overlay icons now class attributes shared between all instances and only created on first init rather than every time the pixmap is recalculated. They have to remain as instance attributes for CollectableMarkers as different collectable types can be different colours.

### CODE REVIEW

**Comment by matzman666** [comment]
I think you need to merge the master branch into your collectables branch. Otherwise there will be conflicts with each pull request.

**Comment by akamal** [comment]
Still not entirely sure the best workflow is for git, from what I've read it looks like the simplest option to avoid conflicts is a new branch for each pull request? That feels weird from my svn tinted view of the world, but I'll give that a go. 

I've also noticed that I must have been tired when I finished up the Collectables feature as there are subtle bugs all over the place: the ref before assignment and repeated checkbox creation you spotted, plus the checkbox state not getting properly persisted and few others. Sorry about that! I'll created a new branch, and get things cleaned up. 

When are you aiming to do the next release?

**Comment by matzman666** [comment]
What you are referring to is the feature branch method. The usual workflow with this method it that each feature is developed in it's own branch (the so-called feature branch), and after merging it into the master branch you delete the old feature branch (or keep it but don't use it anymore) and create a new feature branch from the newest master for the next feature.

Errors happen, don't take them too seriously.

My current plan for releasing the next version is this weekend or the beginning of the next week. Did you have a look at the new icon? How do you like it? I think it's a good looking program icon, but I am not sure about using it as window icon. We also need a multi-res .ico version of it. Could you please do one?

**Comment by akamal** [comment]
I'm not worried about it, just conscious of not making your life unnecessarily difficult when comes to accepting the pull requests!

The icon looks good, as a window icon I think it would look better without the black background though. As it is, it's going to hard to scale down to 16x16 without it becoming just an indistinct blob. Do you/monsto have a copy without the background?
Either way, I should be able to get it converted to an ico by the weekend, along with the revised Location icons and some improvements/fixes to the Collectables feature.

**Comment by matzman666** [comment]
Monsto also gave me these:
http://imgur.com/a/1do1W
http://imgur.com/a/9rWx6

**Pull request merged**
